### ISSUE TITLE
build nvtop on ubuntu18.04 error

### ISSUE THREAD

**Issue by Kevin201806** [Syllo/nvtop#94]
I want to bulild nvtop on my laptop, ant it gave me an error.
error message:
`[ 12%] Building C object src/CMakeFiles/nvtop.dir/nvtop.c.o
In file included from /home/ubuntu/nvtop/include/nvtop/interface.h:25:0,
                 from /home/ubuntu/nvtop/src/nvtop.c:32:
/home/ubuntu/nvtop/include/nvtop/extract_gpuinfo.h:76:3: error: unknown type name ‘nvmlDevice_t’
   nvmlDevice_t device_handle;                     // Used to query device
   ^~~~~~~~~~~~
/home/ubuntu/nvtop/include/nvtop/extract_gpuinfo.h:77:20: error: ‘NVML_DEVICE_NAME_BUFFER_SIZE’ undeclared here (not in a function); did you mean ‘_PC_REC_MAX_XFER_SIZE’?
   char device_name[NVML_DEVICE_NAME_BUFFER_SIZE]; // Device Name
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    _PC_REC_MAX_XFER_SIZE
/home/ubuntu/nvtop/include/nvtop/extract_gpuinfo.h:108:3: error: unknown type name ‘nvmlProcessInfo_t’
   nvmlProcessInfo_t *process_infos;  // Internal use
   ^~~~~~~~~~~~~~~~~
src/CMakeFiles/nvtop.dir/build.make:62: recipe for target 'src/CMakeFiles/nvtop.dir/nvtop.c.o' failed
make[2]: *** [src/CMakeFiles/nvtop.dir/nvtop.c.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'src/CMakeFiles/nvtop.dir/all' failed
make[1]: *** [src/CMakeFiles/nvtop.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

i use this code to build it:
sudo apt install cmake libncurses5-dev libncursesw5-dev git
git clone https://github.com/Syllo/nvtop.git
mkdir -p nvtop/build && cd nvtop/build
cmake ..
cmake .. -DNVML_RETRIEVE_HEADER_ONLINE=True
make               # it gave me the error here

**Comment by linguohua** [comment]
Hi, I encounter the same error when build on ubuntu18.04, and I address it by follow the tips in #49

**Comment by Syllo** [comment]
This shouldn't be a problem anymore with the latest version.
The library is not required for the compilation anymore.
